platform :ios, '10.0'

use_frameworks!

## Without use_frameworks!
target 'Segment-Firebase_Example' do
  # Use default subspec
  pod 'Segment-Firebase', :path => '../'
  
  target 'Segment-Firebase_Tests' do
    inherit! :search_paths

    pod 'OCMockito'
    pod 'Specta'
    pod 'Expecta'
  end
end


## With use_frameworks!
# Use only 'Segment-Firebase/StaticLibWorkaround'

#use_frameworks!
#
#target 'Segment-Firebase_Example' do
#    pod 'Segment-Firebase/StaticLibWorkaround', :path => '../'
#    pod 'Firebase'
#
#end
#
#target 'Segment-Firebase_Tests' do
#    inherit! :search_paths
#
#    pod 'Specta'
#    pod 'Expecta'
#    pod 'OCMockito'
#end
