
target 'Segment-Firebase_Example' do
  pod 'Segment-Firebase', :path => '../'

  target 'Segment-Firebase_Tests' do
    inherit! :search_paths

    pod 'OCMockito'
    pod 'Specta'
    pod 'Expecta'
  end
end
